/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gwsoft_singleeye_SingleEye */

#ifndef _Included_com_gwsoft_singleeye_SingleEye
#define _Included_com_gwsoft_singleeye_SingleEye
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gwsoft_singleeye_SingleEye
 * Method:    onResponse
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_gwsoft_singleeye_SingleEye_onResponse
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
